### ISSUE TITLE
Doesn't install anything on N3DS 9.0

### ISSUE THREAD

**Issue by urherenow** [profi200/sysUpdater#3] opened 2015-05-05 14:34 UTC
When I try to run this, it goes through the list really fast with 0xD8E007F7 next to the name of each .cia file. Also, building it seems to make the NinjHax type files and an .elf. How is this used on emunand then? I've never been able to launch Ninjhax from emunand. I need to update my N3DS (sys or emunand does not matter; I am hard modded) to 9.5. I haven't been able to do this without bricking my emunand using Gateway.

**Comment by profi200** [comment] 2015-05-05 19:03
0xD8E007F7 means it uses an invalid handle which is caused by missing am:u access. There is a release tab on github. The current version contains a CIA.

https://github.com/profi200/sysUpdater/releases

Don't run this on Gateway system NAND or it will brick!

**Comment by urherenow** [comment] 2015-05-06 12:00
How else can you run it as a .CIA, other than with Gateway? Use Gateway to install it then it will runn in Palentine or PBT or whatever those CFWs are called? More to the point, how can you make it work under Ninjhax? libkhaxr, brahma, or bootstrap? If it doesn't run under ninjhax, I have to ask again, why does it automatically build to a .3dsx file?

**Comment by archshift** [comment] 2015-05-06 14:55
If you want to run it with Ninjhax, use libkhax.

**Comment by profi200** [comment] 2015-05-06 20:06
It's not my fault. Gateway broke FIRM installation. At least with this am command.
It builds to 3dsx because that is the default makefile. I have not added my stuff for CIA building to it yet.

**Comment by urherenow** [comment] 2015-05-06 22:30
You don't seem to understand... I've tried using multiple .cia installers, including from Ninjhax, so you can't blame Gateway. I've ONLY been trying sysupdater with Ninjhax and it doesn't install a damn thing. Power on->launch Ninjhax->run libkhax->sysupdater->0xD8E07F7.

**Comment by archshift** [comment] 2015-05-06 22:34
That isn't how you would use it with libkhax. Libkhax needs to be compiled in, and the function to enable all services needs to be called from sysUpdater for it to take effect.

**Comment by profi200** [comment] 2015-05-07 12:43
^

I had no plan yet to build libhax into it. There is also an alternative for Ninjhax in the works which will grant all required permissions. The 3dsx build is more of a preparation for when an alternative appears.

As soon as my ctrulib changes are merged i will start to improve it.

**Closed** 2015-05-27 21:10 UTC
